#!/bin/bash

TEMPLATES="seiscomp msrtsimul import_dlsv import_nettab sync_nettab extr_file nettab2xml"
NOLINKS="run_with_lock trylock waitlock"

export SEISCOMP_ROOT="$(pwd)"
echo "SeisComP home directory: $SEISCOMP_ROOT"

if [ ! -r "lib/keyutils.sh" ]; then
    echo "Cannot read $SEISCOMP_ROOT/lib/keyutils.sh"
    exit 1
fi

source "lib/keyutils.sh"

global_cfg="templates/global.cfg"
if [ ! -r "$global_cfg" ]; then
    echo "Cannot read $SEISCOMP_ROOT/$global_cfg!"
    exit 1
fi

mkdir -p lib
mkdir -p bin

LoadConfig $global_cfg

echo "Creating $SEISCOMP_ROOT/lib/env.sh"
OutputFile templates/env.sh.tpl >"$SEISCOMP_ROOT/lib/env.sh"

for f in $TEMPLATES; do
    rm -f bin/$f
    echo "Creating $SEISCOMP_ROOT/bin/$f"
    OutputFile templates/$f.tpl >bin/$f
    chmod a+x bin/$f
done

for p in pkg/[0-9]*; do
    $p setup
done

AskYN SYMLINKS "Create symbolic links in ~/bin" "no"

if [ "$SYMLINKS" = yes ]; then
    mkdir -p ~/bin
    ( if cd ~/bin; then
        for f in "$SEISCOMP_ROOT"/bin/*; do
            if echo "$NOLINKS" | grep -v "\<${f##*/}\>" >/dev/null; then
                ln -sf "$f" .
            fi
        done
    fi )
fi

echo

